187 ticket dr 04 deployment and validation mechanism for delayed reveal
OfflineHQ/marketplace pull request #207
Opened 2023-12-08 08:50 UTC by AlexandreG-tech

## Type
Enhancement, Bug fix

___
## Description
This PR introduces several enhancements and bug fixes to the NFT Collection deployment process. The main changes include:
- Refactoring of the `deployACollection` method to use a `DeployACollectionProps` object instead of individual parameters.
- Introduction of `CollectionType` enum to distinguish between default and delayed reveal collections.
- Addition of error handling classes `PlaceholderNftUndefinedError` and `CollectionDeploymentError` to provide more specific error messages.
- Addition of private methods `getCommonProps`, `deployAnNftDropCollection`, and `deployDelayedRevealCollection` to modularize the deployment process.
- Addition of a password generation method for delayed reveal collections.

___
## PR changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>index.ts&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        libs/nft/thirdweb-organizer/src/index.ts<br><br>
        <strong>The `NftCollection` class has been significantly refactored. <br>The `deployACollection` method now uses a <br>`DeployACollectionProps` object for its parameters. Two new <br>error classes have been added for better error handling. The <br>deployment process has been broken down into smaller, more <br>manageable methods. A password generation method has been <br>added for delayed reveal collections.</strong>
      </ul>
    </details>
  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/207/files#diff-80b26817489489d8498897af632d05d0f4662c8d8ebdcb70de6613f0297b72d6"> +234/-20</a></td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +enum CollectionType {
Utiliser celui de Hasura dans shared

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +};
Inherit from existing types

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +  description?: string;
regarde si un type existant peut etre utilise via le existant

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +        default:
error

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +      eventId: props.eventId,
pq ne pas spread ? ...props

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +    chainId: string;
pq en inline et pas un type ou interface ?

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
>          'nft-drop',
use the enum from thirdweb or a const

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +    return password.substring(0, 32);
use crypto lib instead

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +      eventSlug: string;
type

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +        'nft-drop',
enum ou const

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +        {
isoler dans une fonction

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +          image: metadata.image,
faire une fonction

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +      const metadatas = Array.from({ length: maxAmount }).map((_, i) => {
Pour les donnees delayed reveal utiliser `getEventPassDelayedRevealedFromEventPassIdOrganizer`

2023-12-08 09:18 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +            metadata,
create a function

2023-12-11 10:20 UTC, sebpalluel reviewed
Isoler ce qui est commun dans les deux deploy dans une fonction commune 'deployDropContractAndPrepareMetadata` :
1. deploy nft drop contract
2. claim conditions
3. create metadata (array de NFT)

Intégrer la difference pour déploy 'normal' et 'delayed_reveal'

Autre fonction avec Hasura a la fin du deploy, `saveEventPassContractIntoDb`:
1. create eventPassNftContract
2. create Hasura metadata (copie de Array NFT pour mettre en db) et avec ça eventPassNfts
3. createEventParametersAndWebhook

2023-12-11 10:20 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +  eventSlug: string;
Use `GetEventPassOrganizerFolderPath` instead
```
import {
  getEventPassOrganizerFolderPath,
  type GetEventPassOrganizerFolderPath,
} from '@features/pass-common';
```

2023-12-11 10:20 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +}
EventPass, GetEventPassOrganizerFolderPath

2023-12-11 13:21 UTC, sebpalluel requested changes
Pb sur `deployDelayedRevealCollection`. Preuve qu'il manque des test car ça t'a échappé. La couverture est satisfaisante sauf pour les fonctions `deployAnNftDropCollection` et `deployDelayedRevealCollection` qui n'ont aucun test.

2023-12-11 13:21 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +      chainId: string;
Confus.

Pq ` & {
      contractAddress: string;
      eventPassId: string;
      chainId: string;...` ?
C'est redondant, inutile même.
      
 D'autre part c'est plus élégant d'utiliser les types intersection
 Voilà le même résultat seulement plus élégant, lisible:
 ```
 type EventPassNftContractObject = Required<
  Pick<
    EventPassNftContract_Insert_Input,
    | 'type'
    | 'contractAddress'
    | 'eventPassId'
    | 'chainId'
    | 'eventId'
    | 'organizerId'
  >
> &
  EventPassNftContract_Insert_Input;
  ```

2023-12-11 13:21 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +      chainId: string;
Même résultat. Tu as la liste en required qui conserve les types de `EventPassNftContract_Insert_Input` et le reste qui est de toute façons en partial.

2023-12-11 13:21 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +          type: EventPassNftContractType_Enum.Normal,
Delayed_Reveal ...

2023-12-11 13:28 UTC, sebpalluel requested changes
Couverture satisfaisante des tests ormi pour `deployAnNftDropCollection` et `deployDelayedRevealCollection` qui ne sont pas du tout couvert alors que ce sont des fonctions compliquée. Manque au minimum un test happy path avec check des args de fonctions appelées pour chacune des deux.

2023-12-11 13:30 UTC, sebpalluel requested changes

2023-12-11 13:30 UTC, sebpalluel commented on libs/nft/thirdweb-organizer/src/index.ts
> +        default:
Throw an error

2023-12-11 13:50 UTC, AlexandreG-tech commented on libs/nft/thirdweb-organizer/src/index.ts
> +      chainId: string;
Intéressant en effet, je me suis compliqué la vie à Omit, j'avais pas vu ça sous cette angle

2023-12-11 13:59 UTC, AlexandreG-tech commented on libs/nft/thirdweb-organizer/src/index.ts
> +          type: EventPassNftContractType_Enum.Normal,
En effet, je n'avais pas push cette correction, réglé

2023-12-12 11:01 UTC, sebpalluel approved these changes

2023-12-12 15:33 UTC, sebpalluel approved these changes

2023-12-12 15:39 UTC, merged