eventPassCardFooter: add next intl provider for EventPassContractReve…
OfflineHQ/marketplace pull request #271
Opened 2024-02-08 08:11 UTC by AlexandreG-tech

## **User description**
…alContractButton and mock next/cache for test in updateEventPassCart

EventPasses.tsx and PasCardSelect.tsx : added NextIntlProvider

migration: change order_amount_handling to not count quantity on update

payment-admin: integration tests to make sure stripeCheckoutSession is deleted if the execution of the function goes right

updateEventPassCart: change migration to not count existing pendingOrder quantity in total quantity and added tests for those edge cases

cart/purchase : reason in search params

stripe process: add button and action to cancel a purchase order and a stripe session, added tests for the getStripeActiveCheckoutSession function and especially the no user/user mail case

lowercase for all eth addresses : update tests and add migration for the insert trigger ; make the cancel my purchase button reactive

___

## **Type**
Enhancement

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>17 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>nftActivity.integration.test.ts
</strong><dd><code>Update <code>fromAddress</code> and <code>toAddress</code> to use lowercase addresses in <br><code>nftActivity.integration.test.ts</code></code></dd></summary>
<hr>

libs/indexer/alchemy/webhooks/src/lib/nftActivity.integration.test.ts
<li>Updated the <code>fromAddress</code> and <code>toAddress</code> values in the <code>mockActivity</code> and <br><code>mockActivity2</code> objects to use lowercase addresses.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/271/files#diff-c098e6c6ba11ed0de016ab4337d7f5e533a5134bf9965b280f4ea64e8177b40c"></a></td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>packCollection.integration.test.ts
</strong><dd><code>Update <code>contractAddress</code> to use lowercase addresses in <br><code>packCollection.integration.test.ts</code></code></dd></summary>
<hr>

libs/nft/thirdweb-organizer/src/packCollection.integration.test.ts
<li>Updated the <code>contractAddress</code> values in the <code>mockActivity</code> and <br><code>mockActivity2</code> objects to use lowercase addresses.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/271/files#diff-548fbfa3ab145e3f1f4cb9a6a7b6fb8f863c4773a614ba058ace31bb2b889fc9"></a></td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pendingOrder.spec.ts
</strong><dd><code>Add <code>eventPass3</code> and test case for updating order with new quantity in <br><code>pendingOrder.spec.ts</code></code></dd></summary>
<hr>

libs/gql/user/api/src/queries/cart/pendingOrder.spec.ts
<li>Added <code>eventPass3</code> object with a lowercase <code>contractAddress</code> value.<br> <li> Added a test case to check the update of an order with a new quantity <br>that exceeds the max limit.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/271/files#diff-bbdec54c1ef7348b3a49901320f7ea6c89954c2f928e3db1f6ad6305039236bf"></a></td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>payment-admin.integration.test.ts
</strong><dd><code>Add integration tests for <code>confirmedStripeCheckoutSession</code> in <br><code>payment-admin.integration.test.ts</code></code></dd></summary>
<hr>

libs/payment/admin/src/lib/payment-admin.integration.test.ts
<li>Added integration tests for the <code>confirmedStripeCheckoutSession</code> <br>function.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/271/files#diff-9abbd512a75f8ae7511d08a1ff32e0c7e0430dcf0401e49f4984f7a31b532fda"></a></td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>BoundedNumericStepper.tsx
</strong><dd><code>Refactor <code>BoundedNumericStepper</code> to use <code>value</code> prop and <code>onChange</code> callback <br>in <code>BoundedNumericStepper.tsx</code></code></dd></summary>
<hr>

libs/ui/components/src/lib/bounded-numeric-stepper/BoundedNumericStepper.tsx
<li>Removed the <code>useState</code> hook and replaced it with a <code>value</code> prop and <br><code>onChange</code> callback.<br> <li> Updated the <code>increment</code> and <code>decrement</code> functions to use the <code>value</code> prop <br>and <code>onChange</code> callback.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/271/files#diff-07fe8623ed00572e51cbe60efc025365d8227ca2292f3517f1a0dadf95ebfbe6"></a></td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>UserCart.tsx
</strong><dd><code>Add `reason` prop and section to `UserCart` in `UserCart.tsx`</code>&nbsp; &nbsp; </dd></summary>
<hr>

libs/features/cart/src/lib/UserCart/UserCart.tsx
<li>Added a new prop <code>reason</code> to <code>UserCartProps</code> and <code>UserCart</code> component.<br> <li> Added a new section in <code>UserCart</code> to display an alert if <code>reason</code> prop is <br>provided.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/271/files#diff-b7f73370b26d73e710d56b085d16d51e0727994905da20570c56e512bc1cf269"></a></td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>PassCardSelect.tsx
</strong><dd><code>Add `value` prop to `PassCardSelect` in `PassCardSelect.tsx`</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/features/organizer/event/src/lib/molecules/PassCard/PassCardSelect.tsx
<li>Added a new prop <code>value</code> to <code>PassCardSelectProps</code> and <br><code>PassCardSelectContent</code> component.<br> <li> Updated the <code>PassCardSelectContent</code> component to use the <code>value</code> prop.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/271/files#diff-f7eb4096cc252d96098d2f0345c3cc33c221eabcd39b773c94025ff609e7d509"></a></td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>PassPurchaseHeader.tsx
</strong><dd><code>Add <code>CancelPurchaseButton</code> component to <code>PassPurchaseHeader</code> in <br><code>PassPurchaseHeader.tsx</code></code></dd></summary>
<hr>

libs/features/organizer/event/src/lib/molecules/PassPurchaseHeader/PassPurchaseHeader.tsx
<li>Added a new component <code>CancelPurchaseButton</code> to handle canceling a <br>purchase order.<br> <li> Updated the <code>PurchaseInProgressAlert</code> component to include the <br><code>CancelPurchaseButton</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/271/files#diff-38096d483193006b2546d0eb5279724cd43f98ed9b478f83a6dbf9c905335671"></a></td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>CancelPurchaseButtonClient.tsx
</strong><dd><code>Add <code>CancelPurchaseButton</code> component to handle canceling a purchase <br>order in <code>CancelPurchaseButtonClient.tsx</code></code></dd></summary>
<hr>

libs/features/organizer/event/src/lib/molecules/PassPurchaseHeader/CancelPurchaseButtonClient.tsx
<li>Added a new component <code>CancelPurchaseButton</code> to handle canceling a <br>purchase order.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/271/files#diff-3dd1fa2ea93cce4f8a017510d7eebd47a1513554e334321f7e1c6ab334aa6257"></a></td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>CartCancelled.stories.tsx
</strong><dd><code>Add story for <code>CartCancelled</code> component with cancel purchase button in <br><code>CartCancelled.stories.tsx</code></code></dd></summary>
<hr>

libs/features/cart/src/lib/CartCancelled/CartCancelled.stories.tsx
<li>Added a new story for <code>CartCancelled</code> component with cancel purchase <br>button.<br>

</details>
    

  </td>
  <td><a [...]

2024-02-08 14:55 UTC, sebpalluel requested changes

2024-02-08 14:55 UTC, sebpalluel commented on hasura/app/migrations/default/1707365734019_insert_lowercase_trigger/up.sql
> +    NEW."contractAddress" := LOWER(NEW."contractAddress");
In this case we need to apply the lowercase also on update for currentOwnerAddress because it's updated.
+ Same applies for `packNftSupply` that is missing.
+ add trigger for `packNftContract`

2024-02-08 14:55 UTC, sebpalluel commented on libs/features/back-office/events/src/lib/molecules/EventPassFilesUploader/EventPassFilesUploader.tsx
> +export async function EventPassFilesUploader(props: EventPassFilesTableProps) {
Not necessary, Suspense handle the async from the children `EventPassFilesUploaderContent` that is indeed asynchronous.

2024-02-08 14:55 UTC, sebpalluel commented on libs/features/organizer/event/src/lib/commons/action.ts
> +'use server';
Add unit test for this one

2024-02-08 14:55 UTC, sebpalluel commented on libs/features/organizer/event/src/lib/molecules/PassCard/PassCardSelectClient.tsx
>      <BoundedNumericStepper
Would be better to use a revalidateTag on the action (to avoid weird UX on the Sheet and intercepted route so pass purchase card version), instead of router.refresh, if nextjs is not buggy as it used to with this

2024-02-08 16:58 UTC, AlexandreG-tech commented on libs/features/organizer/event/src/lib/molecules/PassCard/PassCardSelectClient.tsx
>      <BoundedNumericStepper
Without the router.refresh on the first completion of the onChange function, it seems to switch to the /purchase instead of staying on the sheet .purchase, could be a revalidateTag causing a reload and eventually loading the /purchase because of the URL

2024-02-09 14:39 UTC, sebpalluel requested changes

2024-02-09 14:39 UTC, sebpalluel commented on libs/features/back-office/events/src/lib/molecules/EventPassFilesUploader/EventPassFilesUploader.tsx
> +export async function EventPassFilesUploader(props: EventPassFilesTableProps) {
Well no the issue here really is the `'use server';` at the top of the file that should be removed.

2024-02-09 14:39 UTC, sebpalluel commented on hasura/app/migrations/default/1707365734019_squashed/up.sql
> +
We need to give a name after the unix timestamp that say shortly what's the migration about

2024-02-09 15:23 UTC, sebpalluel approved these changes

2024-02-09 15:23 UTC, sebpalluel commented on libs/features/back-office/events/src/lib/molecules/EventPassFilesUploader/EventPassFilesUploader.tsx
> +export async function EventPassFilesUploader(props: EventPassFilesTableProps) {
That way in the client context it's going to be a client component and on the server side a RSC. If it works ?

2024-02-09 15:23 UTC, sebpalluel commented on libs/features/back-office/events/src/lib/molecules/EventPassFilesUploader/EventPassFilesUploader.tsx
> +export async function EventPassFilesUploader(props: EventPassFilesTableProps) {
Oh no you are right, we are using `getTranslations` from server so never mind

2024-02-09 15:23 UTC, merged